spring.application.name=notesapp

#MySQL connection config
spring.datasource.url=jdbc:mysql://localhost:3306/NotesDB
spring.datasource.username=dev
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.format_sql=true

#Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Config
jwt.secret=4264ebc3a282cb413bf0fcca2e3d7a41318ca0ae13532c69384f00581c35a789
jwt.expiration=360000